app: freshping-telegram
service: freshping-telegram

provider:
  name: aws
  stage: dev
  region: ap-southeast-1
  runtime: nodejs12.x
  logRetentionInDays: 30
  environment:
    BOT_TOKEN: "${opt:botToken}"

functions:
  webhook:
    handler: src/webhook.handler
    events:
      - http:
          path: /{chat_id}
          method: post
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 30
    maxConcurrentRequests: 5